// ═══════════════════ WORD DATA ═══════════════════

export const wordData = [
  // ─── Food & Kitchen ───
  { value: "Roti", hint: "Circle" },
  { value: "Dal", hint: "Flow" },
  { value: "Rice", hint: "Scatter" },
  { value: "Chai", hint: "Break" },
  { value: "Samosa", hint: "Corner" },
  { value: "Jalebi", hint: "Loop" },
  { value: "Lassi", hint: "Blend" },
  { value: "Pickle", hint: "Aging" },
  { value: "Tiffin", hint: "Pause" },
  { value: "Pressure Cooker", hint: "Whistle" },
  { value: "Paratha", hint: "Layer" },
  { value: "Idli", hint: "Soft" },
  { value: "Dosa", hint: "Fold" },
  { value: "Pani Puri", hint: "Burst" },
  { value: "Biryani", hint: "Aroma" },
  { value: "Ketchup", hint: "Dip" },
  { value: "Paneer", hint: "Press" },
  { value: "Butter", hint: "Spread" },
  { value: "Milk", hint: "Boil" },
  { value: "Curd", hint: "Set" },
  { value: "Ghee", hint: "Drip" },
  { value: "Egg", hint: "Crack" },
  { value: "Chicken", hint: "Cook" },
  { value: "Maggi", hint: "Quick" },
  { value: "Pav Bhaji", hint: "Mash" },
  { value: "Chole Bhature", hint: "Puff" },
  { value: "Gulab Jamun", hint: "Soak" },
  { value: "Rasgulla", hint: "Squeeze" },
  { value: "Kulfi", hint: "Freeze" },
  { value: "Paan", hint: "Wrap" },
  { value: "Chapati", hint: "Roll" },
  { value: "Chutney", hint: "Grind" },
  { value: "Raita", hint: "Mix" },
  { value: "Papad", hint: "Crisp" },
  { value: "Khichdi", hint: "Simple" },
  { value: "Halwa", hint: "Sweet" },
  { value: "Ladoo", hint: "Shape" },
  { value: "Barfi", hint: "Slice" },
  { value: "Poha", hint: "Flat" },
  { value: "Upma", hint: "Stir" },

  // ─── Home & Electronics ───
  { value: "Fan", hint: "Rotate" },
  { value: "Cooler", hint: "Relief" },
  { value: "AC", hint: "Closed" },
  { value: "Switch", hint: "Toggle" },
  { value: "Bulb", hint: "Idea" },
  { value: "TV", hint: "Channel" },
  { value: "Remote", hint: "Distance" },
  { value: "Mobile", hint: "Scroll" },
  { value: "Laptop", hint: "Fold" },
  { value: "Charger", hint: "Drain" },
  { value: "Fridge", hint: "Cold" },
  { value: "Freezer", hint: "Solid" },
  { value: "Oven", hint: "Bake" },
  { value: "Microwave", hint: "Heat" },
  { value: "Washing Machine", hint: "Spin" },
  { value: "Iron Box", hint: "Smooth" },
  { value: "Mixer", hint: "Grind" },
  { value: "Geyser", hint: "Warm" },
  { value: "WiFi Router", hint: "Signal" },
  { value: "Bluetooth Speaker", hint: "Pair" },
  { value: "Power Bank", hint: "Backup" },
  { value: "Earphones", hint: "Plug" },
  { value: "Pendrive", hint: "Tiny" },
  { value: "Keyboard", hint: "Type" },
  { value: "Mouse", hint: "Click" },
  { value: "Printer", hint: "Copy" },

  // ─── Bedroom & Bathroom ───
  { value: "Bed", hint: "End" },
  { value: "Pillow", hint: "Sink" },
  { value: "Sofa", hint: "Lounge" },
  { value: "Chair", hint: "Posture" },
  { value: "Table", hint: "Surface" },
  { value: "Mirror", hint: "Reverse" },
  { value: "Comb", hint: "Lines" },
  { value: "Shampoo", hint: "Lather" },
  { value: "Soap", hint: "Slip" },
  { value: "Toothbrush", hint: "Routine" },
  { value: "Towel", hint: "Dry" },
  { value: "Bucket", hint: "Fill" },
  { value: "Mug", hint: "Pour" },
  { value: "Tap", hint: "Flow" },
  { value: "Curtain", hint: "Cover" },
  { value: "Door", hint: "Entry" },
  { value: "Window", hint: "View" },
  { value: "Lock", hint: "Secure" },
  { value: "Key", hint: "Turn" },
  { value: "Balcony", hint: "Edge" },
  { value: "Terrace", hint: "Top" },
  { value: "Almirah", hint: "Store" },
  { value: "Hanger", hint: "Hook" },
  { value: "Clock", hint: "Tick" },
  { value: "Alarm", hint: "Ring" },
  { value: "Dustbin", hint: "Toss" },
  { value: "Broom", hint: "Sweep" },

  // ─── Transport & Travel ───
  { value: "Helmet", hint: "Impact" },
  { value: "Bike", hint: "Balance" },
  { value: "Car", hint: "Lane" },
  { value: "Bus", hint: "Stop" },
  { value: "Train", hint: "Track" },
  { value: "Metro", hint: "Rush" },
  { value: "Ticket", hint: "Access" },
  { value: "Road", hint: "Stretch" },
  { value: "Signal", hint: "Pause" },
  { value: "Police", hint: "Authority" },
  { value: "Auto Rickshaw", hint: "Meter" },
  { value: "Scooter", hint: "Kick" },
  { value: "Cycle", hint: "Pedal" },
  { value: "Airplane", hint: "Altitude" },
  { value: "Airport", hint: "Gate" },
  { value: "Passport", hint: "Stamp" },
  { value: "Petrol Pump", hint: "Fill" },
  { value: "Toll Plaza", hint: "Pass" },
  { value: "Highway", hint: "Speed" },
  { value: "Bridge", hint: "Cross" },

  // ─── School & Office ───
  { value: "School", hint: "Bell" },
  { value: "Teacher", hint: "Explain" },
  { value: "Student", hint: "Attempt" },
  { value: "Notebook", hint: "Blank" },
  { value: "Pen", hint: "Ink" },
  { value: "Exam", hint: "Pressure" },
  { value: "Result", hint: "Outcome" },
  { value: "Uniform", hint: "Match" },
  { value: "Shoes", hint: "Step" },
  { value: "Bag", hint: "Carry" },
  { value: "Office", hint: "Shift" },
  { value: "Boss", hint: "Command" },
  { value: "Salary", hint: "Cycle" },
  { value: "Meeting", hint: "Circle" },
  { value: "File", hint: "Stack" },
  { value: "Bank", hint: "Vault" },
  { value: "ATM", hint: "Slot" },
  { value: "UPI", hint: "Scan" },
  { value: "Wallet", hint: "Fold" },
  { value: "ID Card", hint: "Verify" },
  { value: "Blackboard", hint: "Chalk" },
  { value: "Library", hint: "Silence" },
  { value: "Canteen", hint: "Queue" },
  { value: "Playground", hint: "Run" },
  { value: "Principal", hint: "Office" },

  // ─── Market & Shopping ───
  { value: "Market", hint: "Noise" },
  { value: "Shop", hint: "Counter" },
  { value: "Vegetables", hint: "Cut" },
  { value: "Fruits", hint: "Peel" },
  { value: "Mall", hint: "Escalator" },
  { value: "Bargain", hint: "Less" },
  { value: "Cash", hint: "Count" },
  { value: "Receipt", hint: "Proof" },
  { value: "Trolley", hint: "Push" },
  { value: "Plastic Bag", hint: "Carry" },

  // ─── Culture & Festivals ───
  { value: "Temple", hint: "Bell" },
  { value: "Mosque", hint: "Call" },
  { value: "Church", hint: "Prayer" },
  { value: "Festival", hint: "Burst" },
  { value: "Diwali", hint: "Glow" },
  { value: "Holi", hint: "Throw" },
  { value: "Wedding", hint: "Vows" },
  { value: "Bride", hint: "Veil" },
  { value: "Groom", hint: "Wait" },
  { value: "Dance", hint: "Rhythm" },
  { value: "Music", hint: "Wave" },
  { value: "Rakhi", hint: "Tie" },
  { value: "Rangoli", hint: "Pattern" },
  { value: "Diya", hint: "Flame" },
  { value: "Firecracker", hint: "Bang" },
  { value: "Dhol", hint: "Beat" },
  { value: "Bangle", hint: "Clink" },
  { value: "Saree", hint: "Drape" },
  { value: "Kurta", hint: "Stitch" },
  { value: "Mehendi", hint: "Paste" },

  // ─── Sports & Games ───
  { value: "Cricket", hint: "Pitch" },
  { value: "Football", hint: "Goal" },
  { value: "Badminton", hint: "Net" },
  { value: "Kabaddi", hint: "Hold" },
  { value: "Kho Kho", hint: "Chase" },
  { value: "Chess", hint: "Check" },
  { value: "Carrom", hint: "Flick" },
  { value: "Ludo", hint: "Dice" },
  { value: "Bat", hint: "Swing" },
  { value: "Ball", hint: "Bounce" },
  { value: "Wicket", hint: "Fall" },
  { value: "Stadium", hint: "Roar" },
  { value: "Trophy", hint: "Lift" },
  { value: "Gym", hint: "Lift" },
  { value: "Yoga", hint: "Stretch" },

  // ─── Nature & Weather ───
  { value: "Rain", hint: "Drop" },
  { value: "Sun", hint: "Rise" },
  { value: "Moon", hint: "Glow" },
  { value: "Cloud", hint: "Drift" },
  { value: "River", hint: "Flow" },
  { value: "Mountain", hint: "Peak" },
  { value: "Tree", hint: "Root" },
  { value: "Flower", hint: "Bloom" },
  { value: "Garden", hint: "Green" },
  { value: "Butterfly", hint: "Flutter" },

  // ─── Celebrities / YouTubers / Gamers ───
  { value: "Virat Kohli", hint: "Chase" },
  { value: "MS Dhoni", hint: "Calm" },
  { value: "Rohit Sharma", hint: "Pull" },
  { value: "Hardik Pandya", hint: "Power" },
  { value: "KL Rahul", hint: "Elegant" },
  { value: "Shah Rukh Khan", hint: "Arms" },
  { value: "Salman Khan", hint: "Entry" },
  { value: "Aamir Khan", hint: "Perfect" },
  { value: "Ranveer Singh", hint: "Energy" },
  { value: "Ranbir Kapoor", hint: "Intense" },
  { value: "Deepika Padukone", hint: "Grace" },
  { value: "Alia Bhatt", hint: "Range" },
  { value: "Katrina Kaif", hint: "Dance" },
  { value: "Shraddha Kapoor", hint: "Voice" },
  { value: "Kriti Sanon", hint: "Rise" },
  { value: "CarryMinati", hint: "Roast" },
  { value: "Ashish Chanchlani", hint: "Laugh" },
  { value: "Bhuvan Bam", hint: "Faces" },
  { value: "Technical Guruji", hint: "Gadget" },
  { value: "Triggered Insaan", hint: "React" },
  { value: "Mortal", hint: "Clutch" },
  { value: "Scout", hint: "Aggro" },
  { value: "Dynamo", hint: "Spray" },
  { value: "Jonathan Gaming", hint: "Aim" },
  { value: "Payal Gaming", hint: "Stream" },

  // ─── Everyday Objects ───
  { value: "Newspaper", hint: "Morning" },
  { value: "Glasses", hint: "Vision" },
  { value: "Watch", hint: "Wrist" },
  { value: "Ring", hint: "Band" },
  { value: "Chain", hint: "Link" },
  { value: "Umbrella", hint: "Open" },
  { value: "Raincoat", hint: "Drip" },
  { value: "Torch", hint: "Beam" },
  { value: "Matchbox", hint: "Strike" },
  { value: "Candle", hint: "Melt" },
  { value: "Thread", hint: "Sew" },
  { value: "Needle", hint: "Point" },
  { value: "Scissors", hint: "Snip" },
  { value: "Tape", hint: "Stick" },
  { value: "Glue", hint: "Bond" },
  { value: "Battery", hint: "Charge" },
  { value: "Compass", hint: "North" },
  { value: "Map", hint: "Route" },
  { value: "Calendar", hint: "Date" },
  { value: "Stamp", hint: "Press" },

  // ─── Health & Body ───
  { value: "Doctor", hint: "Cure" },
  { value: "Hospital", hint: "Ward" },
  { value: "Injection", hint: "Prick" },
  { value: "Tablet", hint: "Dose" },
  { value: "Thermometer", hint: "Degree" },
  { value: "Mask", hint: "Cover" },
  { value: "Sanitizer", hint: "Clean" },
  { value: "Bandage", hint: "Wrap" },
  { value: "Ambulance", hint: "Siren" },
  { value: "Stethoscope", hint: "Listen" },

  // ─── NEW CATEGORY: POLITICIANS ───
  { value: "Narendra Modi", hint: "Speech" },
  { value: "Rahul Gandhi", hint: "Debate" },
  { value: "Amit Shah", hint: "Strategy" },
  { value: "Arvind Kejriwal", hint: "Delhi" },
  { value: "Yogi Adityanath", hint: "State" },
  { value: "Mamata Banerjee", hint: "Bengal" },
  { value: "Nitish Kumar", hint: "Alliance" },
  { value: "Lalu Prasad Yadav", hint: "Rail" },
  { value: "Sonia Gandhi", hint: "Congress" },
  { value: "Smriti Irani", hint: "Minister" },

  // ─── NEW CATEGORY: FAMOUS PEOPLE ───
  { value: "Ratan Tata", hint: "Legacy" },
  { value: "Mukesh Ambani", hint: "Wealth" },
  { value: "Gautam Adani", hint: "Ports" },
  { value: "Sundar Pichai", hint: "Search" },
  { value: "Satya Nadella", hint: "Cloud" },
  { value: "APJ Abdul Kalam", hint: "Missile" },
  { value: "Neeraj Chopra", hint: "Throw" },
  { value: "Mary Kom", hint: "Punch" },
  { value: "PV Sindhu", hint: "Smash" },
  { value: "Anand Kumar", hint: "Math" },

  // ─── NEW CATEGORY: COUNTRIES ───
  { value: "India", hint: "Diverse" },
  { value: "USA", hint: "Dollar" },
  { value: "China", hint: "Factory" },
  { value: "Japan", hint: "Tech" },
  { value: "Germany", hint: "Cars" },
  { value: "France", hint: "Paris" },
  { value: "UK", hint: "Crown" },
  { value: "Australia", hint: "Kangaroo" },
  { value: "Canada", hint: "Maple" },
  { value: "Brazil", hint: "Football" },

  // ─── NEW CATEGORY: STATES ───
  { value: "Uttar Pradesh", hint: "Population" },
  { value: "Maharashtra", hint: "Mumbai" },
  { value: "Bihar", hint: "History" },
  { value: "Punjab", hint: "Fields" },
  { value: "Rajasthan", hint: "Desert" },
  { value: "Gujarat", hint: "Business" },
  { value: "Tamil Nadu", hint: "Temple" },
  { value: "Karnataka", hint: "IT" },
  { value: "Kerala", hint: "Backwater" },
  { value: "West Bengal", hint: "Culture" },

  // ─── NEW CATEGORY: MOVIES ───
  { value: "Dangal", hint: "Wrestle" },
  { value: "Pathaan", hint: "Spy" },
  { value: "RRR", hint: "Revolt" },
  { value: "KGF", hint: "Gold" },
  { value: "3 Idiots", hint: "College" },
  { value: "Bahubali", hint: "Kingdom" },
  { value: "Pushpa", hint: "Smuggle" },
  { value: "Drishyam", hint: "Cover" },
  { value: "War", hint: "Agent" },
  { value: "Jawan", hint: "Action" },

  // ─── NEW CATEGORY: STATIONERY ───
  { value: "Pencil", hint: "Graphite" },
  { value: "Eraser", hint: "Remove" },
  { value: "Sharpener", hint: "Point" },
  { value: "Scale", hint: "Measure" },
  { value: "Marker", hint: "Highlight" },
  { value: "Glue Stick", hint: "Stick" },
  { value: "Stapler", hint: "Pin" },
  { value: "Highlighter", hint: "Focus" },
  { value: "Sketch Pen", hint: "Color" },
  { value: "Paper Clip", hint: "Hold" },

  // ─── NEW CATEGORY: DAILY USE PRODUCTS ───
  { value: "Colgate", hint: "Teeth" },
  { value: "Lux Soap", hint: "Bath" },
  { value: "Surf Excel", hint: "Wash" },
  { value: "Amul Butter", hint: "Spread" },
  { value: "Parle G", hint: "Biscuit" },
  { value: "Dettol", hint: "Clean" },
  { value: "Clinic Plus", hint: "Hair" },
  { value: "Aashirvaad Atta", hint: "Flour" },
  { value: "Tata Salt", hint: "Iodine" },
  { value: "Dabur Honey", hint: "Sweet" },
];


// ═══════════════════ SENTENCE DATA ═══════════════════

export const sentenceData = [
  // ─── Daily Routine ───
  { value: "I drink chai every morning", hint: "Start" },
  { value: "My mom cooks delicious food", hint: "Origin" },
  { value: "I go to market daily", hint: "Exchange" },
  { value: "We watch TV together at night", hint: "Screen" },
  { value: "I travel by metro to college", hint: "Commute" },
  { value: "I like eating street food", hint: "Impulse" },
  { value: "I wake up early in the morning", hint: "Cycle" },
  { value: "I brush my teeth twice a day", hint: "Routine" },
  { value: "I take bath using bucket water", hint: "Pour" },
  { value: "I wear uniform to school", hint: "Match" },

  // ─── Tech & Phone ───
  { value: "I charge my phone every night", hint: "Restore" },
  { value: "I use earphones while traveling", hint: "Isolate" },
  { value: "I scroll Instagram daily", hint: "Endless" },
  { value: "I chat on WhatsApp", hint: "Ping" },
  { value: "I watch reels before sleeping", hint: "Loop" },
  { value: "I check my phone first thing", hint: "Unlock" },
  { value: "I take selfies everywhere", hint: "Click" },
  { value: "I download apps frequently", hint: "Install" },
  { value: "My phone storage is always full", hint: "Delete" },
  { value: "I screenshot important messages", hint: "Save" },

  // ─── Food & Eating ───
  { value: "I buy vegetables from local market", hint: "Fresh" },
  { value: "I eat roti and sabzi daily", hint: "Staple" },
  { value: "I drink milk before sleeping", hint: "Calm" },
  { value: "I eat fruits in breakfast", hint: "Light" },
  { value: "I prefer home cooked food", hint: "Comfort" },
  { value: "I eat Maggi when I'm lazy", hint: "Quick" },
  { value: "I order food online sometimes", hint: "Deliver" },
  { value: "I eat biryani on weekends", hint: "Treat" },
  { value: "I share my tiffin with friends", hint: "Bond" },
  { value: "I always take seconds of dal", hint: "Repeat" },

  // ─── Culture & Family ───
  { value: "I go to temple with family", hint: "Faith" },
  { value: "I celebrate festivals happily", hint: "Joy" },
  { value: "I apply mehndi on occasions", hint: "Pattern" },
  { value: "I wear traditional clothes", hint: "Culture" },
  { value: "I attend weddings frequently", hint: "Gather" },
  { value: "We celebrate Diwali with lights", hint: "Glow" },
  { value: "I touch elders feet for blessing", hint: "Respect" },
  { value: "I help mom in the kitchen", hint: "Support" },
  { value: "I visit grandparents in summer", hint: "Roots" },
  { value: "We eat dinner together as family", hint: "Unity" },

  // ─── Transport & Safety ───
  { value: "I travel by bus sometimes", hint: "Public" },
  { value: "I ride bike carefully", hint: "Balance" },
  { value: "I follow traffic rules", hint: "Order" },
  { value: "I wear helmet always", hint: "Shield" },
  { value: "I use seatbelt in car", hint: "Secure" },
  { value: "I hate traffic jams", hint: "Stuck" },
  { value: "I always carry my bus pass", hint: "Routine" },
  { value: "I prefer window seat in bus", hint: "Breeze" },
  { value: "I walk to nearby places", hint: "Steps" },
  { value: "I share auto with strangers", hint: "Split" },

  // ─── Health & Wellness ───
  { value: "I visit doctor when sick", hint: "Relief" },
  { value: "I take medicines on time", hint: "Dose" },
  { value: "I drink hot water in winter", hint: "Warm" },
  { value: "I rest when tired", hint: "Pause" },
  { value: "I exercise regularly", hint: "Discipline" },
  { value: "I do yoga in the morning", hint: "Stretch" },
  { value: "I avoid junk food on weekdays", hint: "Control" },
  { value: "I drink eight glasses of water", hint: "Hydrate" },
  { value: "I wash hands before eating", hint: "Clean" },
  { value: "I sleep before midnight", hint: "Recharge" },

  // ─── School & Studies ───
  { value: "I attend online classes sometimes", hint: "Remote" },
  { value: "I study in the evening", hint: "Focus" },
  { value: "I do homework after snacks", hint: "Fuel" },
  { value: "I carry heavy books daily", hint: "Weight" },
  { value: "I sit on the last bench", hint: "Hide" },
  { value: "I copy notes from friends", hint: "Borrow" },
  { value: "I study hard before exams", hint: "Cram" },
  { value: "I ask doubts in class", hint: "Curious" },
  { value: "I participate in competitions", hint: "Compete" },
  { value: "I always lose my eraser", hint: "Vanish" },

  // ─── Sports & Fun ───
  { value: "I play cricket with friends", hint: "Team" },
  { value: "I use my phone a lot", hint: "Habit" },
  { value: "I watch IPL every season", hint: "Season" },
  { value: "I play BGMI with squad", hint: "Drop" },
  { value: "I celebrate every boundary", hint: "Cheer" },
  { value: "I play carrom with siblings", hint: "Flick" },
  { value: "I watch football highlights", hint: "Goal" },
  { value: "I play ludo on my phone", hint: "Dice" },
  { value: "I go cycling on weekends", hint: "Pedal" },
  { value: "I swim in summer vacation", hint: "Dive" },

  // ─── Celebrity Sentences ───
  { value: "I watch Virat Kohli play cricket", hint: "Chase" },
  { value: "I like Shah Rukh Khan movies", hint: "Arms" },
  { value: "I follow CarryMinati on YouTube", hint: "Roast" },
  { value: "I watch Mortal gaming videos", hint: "Clutch" },
  { value: "I enjoy Ashish Chanchlani comedy", hint: "Laugh" },
  { value: "I follow Technical Guruji reviews", hint: "Gadget" },
  { value: "I watch Bhuvan Bam content", hint: "Faces" },
  { value: "I support MS Dhoni team", hint: "Captain" },
  { value: "I like Alia Bhatt acting", hint: "Range" },
  { value: "I watch Scout gameplay", hint: "Aggro" },

  // ─── Social & Friends ───
  { value: "I gossip with my best friend", hint: "Secret" },
  { value: "I go for evening walks", hint: "Breeze" },
  { value: "I borrow money from friends", hint: "Pending" },
  { value: "I share memes in group chat", hint: "Forward" },
  { value: "I make plans and cancel", hint: "Postpone" },
  { value: "I take group photos everywhere", hint: "Pose" },
  { value: "I miss my school friends", hint: "Memory" },
  { value: "I always arrive late", hint: "Delay" },
  { value: "I laugh loudly in public", hint: "Volume" },
  { value: "I give nicknames to everyone", hint: "Label" },

  // ─── Weather & Seasons ───
  { value: "I love rainy weather", hint: "Petrichor" },
  { value: "I eat ice cream in summer", hint: "Melt" },
  { value: "I sleep with blanket in winter", hint: "Cozy" },
  { value: "I hate Monday mornings", hint: "Dread" },
  { value: "I enjoy long drives at night", hint: "Escape" },
  { value: "I sit near window when it rains", hint: "Watch" },
  { value: "I wear sweater in December", hint: "Wool" },
  { value: "I fly kites on Makar Sankranti", hint: "String" },
  { value: "I sip soup on cold nights", hint: "Warm" },
  { value: "I apply sunscreen in summer", hint: "Shield" },

  // ─── Home & Chores ───
  { value: "I clean my room on Sundays", hint: "Tidy" },
  { value: "I water the plants daily", hint: "Nurture" },
  { value: "I iron my clothes at night", hint: "Smooth" },
  { value: "I forget to switch off lights", hint: "Waste" },
  { value: "I set alarm but still oversleep", hint: "Snooze" },
  { value: "I lock the door before leaving", hint: "Check" },
  { value: "I keep my desk messy", hint: "Chaos" },
  { value: "I hide snacks in my room", hint: "Stash" },
  { value: "I fight with siblings for remote", hint: "Battle" },
  { value: "I sing while taking shower", hint: "Echo" },

  // ─── NEW CATEGORY: POLITICIANS ───
  { value: "I listen to Narendra Modi speeches", hint: "Leader" },
  { value: "I watch debates of Rahul Gandhi", hint: "Debate" },
  { value: "I follow Amit Shah strategies", hint: "Plan" },

  // ─── NEW CATEGORY: FAMOUS PEOPLE ───
  { value: "I admire Ratan Tata personality", hint: "Legacy" },
  { value: "I read about APJ Abdul Kalam", hint: "Inspire" },
  { value: "I follow Sundar Pichai journey", hint: "Tech" },

  // ─── NEW CATEGORY: COUNTRIES ───
  { value: "I want to visit USA someday", hint: "Travel" },
  { value: "I like Japanese technology", hint: "Advance" },
  { value: "I watch French movies sometimes", hint: "Cinema" },

  // ─── NEW CATEGORY: STATES ───
  { value: "I want to visit Rajasthan deserts", hint: "Sand" },
  { value: "I love Kerala backwaters", hint: "Boat" },
  { value: "Mumbai is in Maharashtra", hint: "City" },

  // ─── NEW CATEGORY: MOVIES ───
  { value: "I watched Dangal movie twice", hint: "Repeat" },
  { value: "I like Bahubali action scenes", hint: "Epic" },
  { value: "Pushpa dialogues are famous", hint: "Style" },

  // ─── NEW CATEGORY: STATIONERY ───
  { value: "I write notes with pen", hint: "Ink" },
  { value: "I sharpen pencil daily", hint: "Point" },
  { value: "I highlight important lines", hint: "Focus" },

  // ─── NEW CATEGORY: DAILY PRODUCTS ───
  { value: "I brush using Colgate daily", hint: "Clean" },
  { value: "I wash clothes with Surf Excel", hint: "Wash" },
  { value: "I eat Parle G with tea", hint: "Dip" },

];


// ═══════════════════ PHASES ═══════════════════

export const PHASES = {
  SETUP: "SETUP",
  WHEEL_PICKER: "WHEEL_PICKER",
  REVEAL: "REVEAL",
  WHEEL_SPEAKER: "WHEEL_SPEAKER",
  DISCUSSION: "DISCUSSION",
  VOTING: "VOTING",
  INTERMEDIATE_RESULT: "INTERMEDIATE_RESULT",
  RESULT: "RESULT"
};
